# Generated by Django 5.2.8 on 2025-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.IntegerField(default=60)),
                ('portion_grams', models.IntegerField(default=50)),
                ('capacity_max', models.IntegerField(default=1000)),
                ('capacity_current', models.IntegerField(default=1000)),
                ('low_percent', models.IntegerField(default=15)),
                ('next_feed_at', models.DateTimeField(blank=True, null=True)),
                ('last_fed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_fed_at'],
            },
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
