# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feeder_delete_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='behavior_adjustment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='daily_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feeder',
            name='extreme_weather_pause',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='heat_increase_percent',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='feeder',
            name='low_feed_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='missed_feed_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='rain_reduction_percent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='feeder',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval-based'), ('daily', 'Daily schedule'), ('adaptive', 'Weather-adaptive')], default='interval', max_length=20),
        ),
        migrations.AddField(
            model_name='feeder',
            name='smart_optimization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeder',
            name='water_quality_adjustment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='weather_adaptation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeder',
            name='weather_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('scheduled', 'Scheduled Auto Feed'), ('manual', 'Manual Feed'), ('weather_adjusted', 'Weather-Adjusted Feed'), ('smart_adjusted', 'Smart-Adjusted Feed')], default='scheduled', max_length=20)),
                ('portion_grams', models.IntegerField()),
                ('capacity_before', models.IntegerField()),
                ('capacity_after', models.IntegerField()),
                ('weather_conditions', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='api.feeder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
