# Generated by Django 4.2.16 on 2025-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('forecast_type', models.CharField(choices=[('current', 'Current Weather'), ('tomorrow', 'Tomorrow Forecast'), ('daily', 'Daily Forecast')], default='current', max_length=20)),
                ('forecast_date', models.DateField(db_index=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(blank=True, help_text='Feels like temperature', null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(help_text='Weather condition description', max_length=100)),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('pressure', models.FloatField(help_text='Atmospheric pressure in hPa')),
                ('cloud_cover', models.IntegerField(default=0, help_text='Cloud coverage percentage')),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h')),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('wind_degree', models.IntegerField(blank=True, null=True)),
                ('gust_speed', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(default=0.0, help_text='Precipitation in mm')),
                ('visibility', models.FloatField(blank=True, help_text='Visibility in km', null=True)),
                ('uv_index', models.IntegerField(default=0)),
                ('sunrise', models.CharField(blank=True, max_length=20)),
                ('sunset', models.CharField(blank=True, max_length=20)),
                ('moon_phase', models.CharField(blank=True, max_length=50)),
                ('moon_illumination', models.IntegerField(blank=True, null=True)),
                ('weather_icon', models.CharField(blank=True, help_text='Weather icon code', max_length=10)),
                ('temperature_impact', models.CharField(blank=True, choices=[('optimal', 'Optimal'), ('normal', 'Normal'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], max_length=20)),
                ('rain_impact', models.CharField(blank=True, choices=[('normal', 'Normal'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], max_length=20)),
                ('wind_impact', models.CharField(blank=True, choices=[('optimal', 'Optimal'), ('normal', 'Normal'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], max_length=20)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='csv_dataset', help_text='Data source', max_length=50)),
            ],
            options={
                'ordering': ['forecast_date', 'city'],
                'indexes': [models.Index(fields=['city', 'forecast_date'], name='api_weather_city_21fca9_idx'), models.Index(fields=['forecast_type', 'forecast_date'], name='api_weather_forecas_ba7987_idx'), models.Index(fields=['-created_at'], name='api_weather_created_3100ed_idx')],
                'unique_together': {('city', 'forecast_date', 'forecast_type')},
            },
        ),
    ]
