# Generated by Django 4.2.16 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weatherforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={'ordering': ['forecast_date', 'country', 'province', 'municipality', 'city']},
        ),
        # Removed an intermediate AlterUniqueTogether that cleared the unique_together
        # because on some backends (e.g. MySQL) this can attempt to drop a constraint
        # that does not exist on a fresh database and raise a ValueError.
        migrations.AddField(
            model_name='weatherforecast',
            name='municipality',
            field=models.CharField(blank=True, db_index=True, help_text='Municipality or district', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='province',
            field=models.CharField(blank=True, db_index=True, help_text='Province, state, or region', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together={('city', 'province', 'municipality', 'forecast_date', 'forecast_type')},
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['province', 'forecast_date'], name='api_weather_provinc_86b427_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['municipality', 'forecast_date'], name='api_weather_municip_1bae5e_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['country', 'forecast_date'], name='api_weather_country_bec868_idx'),
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='longitude',
        ),
    ]
