# Generated by Django 4.2.16 on 2025-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_weatherforecast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
