# Generated by Django 4.2.16 on 2026-02-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_weatherforecast_latitude_weatherforecast_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_harvest_kg', models.FloatField(default=0.0)),
                ('harvest_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_lead_days', models.IntegerField(default=7)),
                ('harvest_time', models.TimeField(default='08:00:00')),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('pieces', 'Pieces')], default='kg', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('is_all', models.BooleanField(default=False, help_text='Marks harvest-all / end of season')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.season')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_harvest_kg', models.FloatField(default=0.0)),
                ('harvest_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('average_temp', models.FloatField(blank=True, null=True)),
                ('average_ph', models.FloatField(blank=True, null=True)),
                ('average_do', models.FloatField(blank=True, null=True)),
                ('average_tds', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='api_seasonh_user_id_657607_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['user'], name='api_season_user_id_1109e5_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_active'], name='api_season_is_acti_6bb63b_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestentry',
            index=models.Index(fields=['season'], name='api_harvest_season__6895aa_idx'),
        ),
    ]
