# Generated by Django 4.2.16 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_season_historysettings_harvestentry_seasonhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
    ]
