# Generated by Django 4.2.16 on 2026-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_expand_alert_severity_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysettings',
            name='days_before_notification',
            field=models.IntegerField(default=2, help_text='Days before expected harvest to send reminder email'),
        ),
        migrations.AlterField(
            model_name='historysettings',
            name='harvest_lead_days',
            field=models.IntegerField(default=90),
        ),
    ]
