# Generated by Django 4.2.16 on 2026-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_season_harvest_and_setting_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingemail',
            name='user',
        ),
        migrations.AddField(
            model_name='season',
            name='stocking_density',
            field=models.IntegerField(default=0, help_text='Number of shrimp stocked at start'),
        ),
        migrations.DeleteModel(
            name='SeasonHarvest',
        ),
        migrations.DeleteModel(
            name='SettingEmail',
        ),
    ]
