# Generated by Django 4.2.16 on 2026-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_oxygen_to_turbidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='parameter',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('ph', 'pH'), ('turbidity', 'Turbidity'), ('tds', 'TDS')], max_length=20, unique=True),
        ),
    ]
