# Generated by Django 4.2.16 on 2026-05-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_feedertelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('starter', 'Starter Feed (PL5-PL10)'), ('nursery', 'Nursery Feed (PL10-0.5g)'), ('juvenile', 'Juvenile Feed (0.5g-3g)'), ('grower', 'Grower Feed (3g-8g)'), ('finisher', 'Finisher Feed (8g+)'), ('specialty', 'Specialty Feed')], default='grower', max_length=20)),
                ('protein_percent', models.FloatField(help_text='Protein content percentage')),
                ('fat_percent', models.FloatField(help_text='Fat content percentage')),
                ('fiber_percent', models.FloatField(help_text='Fiber content percentage')),
                ('size_microns', models.IntegerField(help_text='Feed pellet size in microns')),
                ('target_min_weight_grams', models.FloatField(help_text='Minimum shrimp weight for this feed')),
                ('target_max_weight_grams', models.FloatField(help_text='Maximum shrimp weight for this feed')),
                ('cost_per_kg', models.FloatField(default=0.0, help_text='Cost per kilogram')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feed Types',
                'ordering': ['target_min_weight_grams'],
            },
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='shrimp_size_adjustment_factor',
            field=models.FloatField(default=1.0, help_text='Multiplier based on average shrimp size'),
        ),
        migrations.AddField(
            model_name='season',
            name='average_shrimp_weight_grams',
            field=models.FloatField(default=0.0, help_text='Average shrimp weight in grams'),
        ),
        migrations.AddField(
            model_name='season',
            name='current_shrimp_quantity',
            field=models.IntegerField(default=0, help_text='Current estimated shrimp count in pond'),
        ),
        migrations.AddField(
            model_name='seasonhistory',
            name='average_shrimp_weight_grams',
            field=models.FloatField(default=0.0, help_text='Average shrimp weight achieved'),
        ),
        migrations.AddField(
            model_name='seasonhistory',
            name='final_shrimp_quantity',
            field=models.IntegerField(default=0, help_text='Shrimp remaining at season end'),
        ),
        migrations.AddField(
            model_name='seasonhistory',
            name='initial_shrimp_quantity',
            field=models.IntegerField(default=0, help_text='Shrimp stocked at season start'),
        ),
        migrations.AddField(
            model_name='seasonhistory',
            name='survival_rate_percent',
            field=models.FloatField(default=0.0, help_text='Survival percentage'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='feed_product',
            field=models.ForeignKey(blank=True, help_text='Specific feed product used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_logs', to='api.feedtype'),
        ),
        migrations.CreateModel(
            name='GrowthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(help_text='Date when prediction was made')),
                ('forecast_date', models.DateField(help_text='Date for which prediction is made')),
                ('predicted_avg_weight_grams', models.FloatField()),
                ('predicted_shrimp_count', models.IntegerField()),
                ('predicted_survival_rate_percent', models.FloatField()),
                ('estimated_harvest_date', models.DateField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence percentage (0-100)')),
                ('recommendation', models.TextField(blank=True, help_text='AI recommendation based on prediction')),
                ('model_version', models.CharField(default='1.0', help_text='ML model version used', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Most recent prediction for this forecast date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_predictions', to='api.season')),
            ],
            options={
                'ordering': ['-forecast_date', '-prediction_date'],
                'indexes': [models.Index(fields=['season', 'forecast_date'], name='api_growthp_season__242711_idx'), models.Index(fields=['is_active', '-forecast_date'], name='api_growthp_is_acti_ebd760_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyGrowthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shrimp_count', models.IntegerField(help_text='Estimated or counted shrimp quantity')),
                ('avg_weight_grams', models.FloatField(help_text='Average shrimp weight in grams')),
                ('daily_weight_gain_grams', models.FloatField(default=0.0, help_text='Weight gained from previous day')),
                ('daily_mortality_percent', models.FloatField(default=0.0, help_text='Mortality percentage for this day')),
                ('feed_amount_grams', models.FloatField(default=0.0, help_text='Feed consumed this day')),
                ('water_temperature', models.FloatField(blank=True, help_text='Water temperature in Celsius', null=True)),
                ('water_ph', models.FloatField(blank=True, null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, help_text='Dissolved oxygen in mg/L', null=True)),
                ('tds', models.FloatField(blank=True, help_text='Total dissolved solids', null=True)),
                ('weather_condition', models.CharField(blank=True, help_text='e.g., sunny, rainy, cloudy', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='api.season')),
            ],
            options={
                'verbose_name_plural': 'Daily Growth Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['season', '-date'], name='api_dailygr_season__785cf7_idx')],
                'unique_together': {('season', 'date')},
            },
        ),
    ]
