# Generated by Django 4.2.16 on 2026-05-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_feedtype_feedinglog_shrimp_size_adjustment_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('api_source', models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('weatherapi', 'WeatherAPI'), ('nasa', 'NASA')], max_length=50)),
                ('month', models.DateField(db_index=True)),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('accuracy_percent', models.FloatField()),
                ('predictions_count', models.IntegerField()),
                ('verified_count', models.IntegerField()),
                ('current_weight', models.FloatField(default=0.33)),
                ('previous_weight', models.FloatField(default=0.33)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'location'],
            },
        ),
        migrations.CreateModel(
            name='ModelRetrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retraining_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('month_end', models.DateField()),
                ('total_predictions', models.IntegerField()),
                ('verified_predictions', models.IntegerField()),
                ('previous_avg_rmse', models.FloatField()),
                ('new_avg_rmse', models.FloatField()),
                ('improvement_percent', models.FloatField()),
                ('xgboost_version', models.CharField(max_length=50)),
                ('lstm_version', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('errors', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-retraining_date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('forecast_date', models.DateTimeField(db_index=True)),
                ('metric', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('rainfall', 'Rainfall'), ('pressure', 'Pressure')], max_length=50)),
                ('ensemble_value', models.FloatField()),
                ('ml_corrected_value', models.FloatField()),
                ('ensemble_confidence', models.FloatField()),
                ('ml_confidence', models.FloatField()),
                ('combined_confidence', models.FloatField(default=50.0)),
                ('open_meteo_value', models.FloatField(blank=True, null=True)),
                ('weatherapi_value', models.FloatField(blank=True, null=True)),
                ('nasa_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('actual_source', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ensemble_error', models.FloatField(blank=True, null=True)),
                ('ml_error', models.FloatField(blank=True, null=True)),
                ('improvement', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='seasonhistory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='seasonhistory',
            name='api_seasonh_user_id_657607_idx',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='average_shrimp_weight_grams',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='final_shrimp_quantity',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='initial_shrimp_quantity',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='seasonhistory',
            name='survival_rate_percent',
        ),
        migrations.AddIndex(
            model_name='weatherprediction',
            index=models.Index(fields=['location', 'metric', '-forecast_date'], name='api_weather_locatio_8221a8_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherprediction',
            index=models.Index(fields=['location', '-created_at'], name='api_weather_locatio_981f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiperformance',
            unique_together={('location', 'api_source', 'month')},
        ),
    ]
