# Generated by Django 4.2.16 on 2026-07-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_apiperformance_modelretraininglog_weatherprediction_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_season_name_per_user'),
        ),
    ]
