# Generated by Django 4.2.16 on 2026-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_unique_season_name_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='today_feed_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
