# Generated by Django 4.2.16 on 2026-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alert_nullable_value_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygrowthmetric',
            name='turbidity',
            field=models.FloatField(blank=True, help_text='Turbidity in NTU (from SensorReading)', null=True),
        ),
        migrations.AlterField(
            model_name='dailygrowthmetric',
            name='dissolved_oxygen',
            field=models.FloatField(blank=True, help_text='Dissolved oxygen in mg/L (optional; not in SensorReading — may be estimated from turbidity)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Report'), ('seasonal', 'Seasonal Report')], default='daily', max_length=20),
        ),
    ]
