# Generated by Django 4.2.16 on 2026-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_dailygrowthmetric_turbidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedertelemetry',
            name='run_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedertelemetry',
            name='run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedertelemetry',
            name='run_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
